### ISSUE TITLE
Open discussion: TTL

### ISSUE THREAD

**Issue by adulau** [adulau/pdns-qof#6]
Should we include TTL? 

- An implementation is doing an average of the TTL
- It's challenging on the aggregation aspect (median, average, mean)
- Maybe an optional field clearly describing the algorithm used
- ttl_min / ttl_max
- appendix for additional clarification

**Comment by aaronkaplan** [comment]
* add information (maybe in the Appendix) to describe these use-cases

**Comment by adulau** [comment]
- Below versus above recursive.
