### ISSUE TITLE
default mime type for pdns output

### ISSUE THREAD

**Issue by adulau** [adulau/pdns-qof#9]
As the output format pdns-qof is newline separated, should we define a new mime-type?

- http://jsonlines.org/ - discussion https://github.com/wardi/jsonlines/issues/9
- https://github.com/ndjson/ndjson-spec

Maybe it's time to ask for a specific mime-type?

**Comment by robtex** [comment]
https://github.com/ndjson/ndjson-spec seems to be exactly what we have, and has a suggested mime-type of application/x-ndjson
i'll pick that for now and see if it will be trending

**Comment by adulau** [comment]
- text/json

**Comment by aaronkaplan** [comment]
so, decision on this?

**Comment by aaronkaplan** [comment]
@adulau ping? what's the decision on this one? Should we add it to the RFC text?

**Comment by djw1149** [comment]
FWIW, we use application/x-ndjson in https://docs.dnsdb.info/dnsdb-apiv2/

**Comment by aaronkaplan** [comment]
Okay, I take it from two to one that "application/x-ndjson" makes the most sense.
If there are not counter opinions, I'll add that by into the i-d text by Sunday evening (2nd of May 2021)

**Comment by aaronkaplan** [comment]
Timeout, adding a sentence that the preferred MIME type is "application/x-ndjson".
